# Generated by Django 5.1.1 on 2024-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('_client_secret', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
