# Generated by Django 5.1.1 on 2024-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('activityid', models.CharField(blank=True, default='', max_length=60)),
                ('datasetname', models.CharField(blank=True, default='', max_length=120)),
                ('issuccess', models.CharField(blank=True, default='', max_length=60)),
                ('itemname', models.CharField(blank=True, default='', max_length=120)),
                ('activity', models.CharField(max_length=120)),
                ('workload', models.CharField(blank=True, default='', max_length=60)),
                ('refreshenforcementpolicy', models.CharField(blank=True, default='', max_length=60)),
                ('operation', models.CharField(max_length=120)),
                ('recordtype', models.CharField(blank=True, default='', max_length=60)),
                ('requestid', models.CharField(blank=True, default='', max_length=60)),
                ('organizationid', models.CharField(max_length=60)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('usertype', models.CharField(blank=True, default='', max_length=60)),
                ('workspaceid', models.CharField(blank=True, default='', max_length=60)),
                ('datasetid', models.CharField(blank=True, default='', max_length=60)),
                ('userid', models.CharField(max_length=60)),
                ('creationtime', models.DateTimeField()),
                ('objectid', models.CharField(blank=True, default='', max_length=255)),
                ('workspacename', models.CharField(blank=True, default='', max_length=120)),
                ('clientip', models.CharField(blank=True, default='', max_length=60)),
                ('userkey', models.CharField(max_length=60)),
                ('artifactkind', models.CharField(blank=True, default='', max_length=60)),
                ('useragent', models.CharField(blank=True, default='', max_length=255)),
                ('artifactid', models.CharField(blank=True, default='', max_length=60)),
                ('capacityid', models.CharField(blank=True, default='', max_length=60)),
                ('capacityname', models.CharField(blank=True, default='', max_length=120)),
                ('artifactname', models.CharField(blank=True, default='', max_length=120)),
                ('lastrefreshtime', models.DateTimeField(blank=True, null=True)),
                ('dataconnectivitymode', models.CharField(blank=True, default='', max_length=60)),
                ('distributionmethod', models.CharField(blank=True, default='', max_length=60)),
                ('reporttype', models.CharField(blank=True, default='', max_length=60)),
                ('reportid', models.CharField(blank=True, default='', max_length=60)),
                ('reportname', models.CharField(blank=True, default='', max_length=120)),
                ('refreshtype', models.CharField(blank=True, default='', max_length=60)),
                ('consumptionmethod', models.CharField(blank=True, default='', max_length=60)),
                ('itemid', models.CharField(blank=True, default='', max_length=60)),
                ('modelssnapshots', models.CharField(blank=True, default='', max_length=255)),
                ('aggregatedworkspaceinformation', models.CharField(blank=True, default='', max_length=255)),
                ('importdisplayname', models.CharField(blank=True, default='', max_length=120)),
                ('importtype', models.CharField(blank=True, default='', max_length=60)),
                ('importid', models.CharField(blank=True, default='', max_length=60)),
                ('importsource', models.CharField(blank=True, default='', max_length=60)),
                ('appname', models.CharField(blank=True, default='', max_length=120)),
                ('appreportid', models.CharField(blank=True, default='', max_length=60)),
                ('appid', models.CharField(blank=True, default='', max_length=60)),
                ('exporteventstartdatetimeparameter', models.DateTimeField(blank=True, null=True)),
                ('exporteventenddatetimeparameter', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEventField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=120, unique=True)),
                ('fieldtype', models.CharField(max_length=60)),
                ('displayname', models.CharField(blank=True, default='', max_length=60)),
                ('displayorder', models.IntegerField(blank=True, default=None, null=True)),
                ('display', models.BooleanField(default=False)),
                ('filter', models.BooleanField(default=False)),
                ('orderby', models.BooleanField(default=False)),
                ('search', models.BooleanField(default=False)),
                ('export', models.BooleanField(default=False)),
                ('chart', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('displayorder'), nulls_last=True), 'fieldname'],
            },
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskuuid', models.CharField(max_length=60, unique=True)),
                ('taskname', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('success', 'SUCCESS'), ('failure', 'FAILURE')], default='PENDING', max_length=10)),
                ('result', models.TextField(default='')),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
